# Change these first
owner: Eloniumm # Your GitHub organization or username, where this repository lives
repo: Status-Page # The name of this repository

sites:
  - name: NA1 - Bot Node
    url: https://google.com
  - name: NA2 - Bot Node
    url: https://nrk.no
  - name: EU1
    url: https://namecheap.com
  - name: AU1
    url: https://nrk.no

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  logoUrl: https://cdn.discordapp.com/icons/901892863405727815/0e90579e7e710064e87370a48a7fb691.png?size=128
  name: "ProCloud"
  introTitle: "Real-Time Node Status"
  introMessage: "Here is where our customers can see the status of their nodes."
  navbar:
    - title: Website
      href: https://procloud.xyz
    - title: Panel
      href: https://panel.procloud.xyz
    - title: Discord
      href: https://discord.gg
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
